[project]
name = "audio-discovery-core"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.discovery-engine]
path = "contracts/discovery-engine.clar"
depends_on = []

[contracts.monetization-layer]
path = "contracts/monetization-layer.clar"
depends_on = []

[contracts.recommendation-engine]
path = "contracts/recommendation-engine.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
